In [ ]:
import pandas as pd
import numpy as np
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
import plotly.io as pio
from umap import UMAP
from hdbscan import HDBSCAN
from pathlib import Path
import time
import stopwordsiso as stopwords
from src.evaluation import TopicEvaluator

In [65]:
DATA_PATH = (
    r"D:\proposal\thiese\code\.venv\data\raw\isna_complete.csv"
)

In [3]:
df = pd.read_csv(DATA_PATH)

documents = (
    df["content"]
    .dropna()
    .astype(str)
    .tolist()
)

print(f"Number of documents: {len(documents)}")

Number of documents: 5969

In [64]:
df.columns

Index(['category', 'sub_category', 'title', 'url', 'content', 'published date',
       'summary', 'news_code'],
      dtype='object')

In [4]:
print("Dataset Shape:")
print(df.shape)

print()

print("Missing Values:")
print(df.isnull().sum())

print()

print("Categories:")
print(df["category"].value_counts())

Dataset Shape:
(5969, 8)

Missing Values:
category          0
sub_category      0
title             0
url               0
content           0
published date    0
summary           0
news_code         0
dtype: int64

Categories:
category
ورزشی            1396
سیاسی            1297
اقتصادی          1266
فرهنگی و هنری    1195
اجتماعی           815
Name: count, dtype: int64

In [6]:
embedding_model = SentenceTransformer(
    "HooshvareLab/bert-base-parsbert-uncased"
)

No sentence-transformers model found with name HooshvareLab/bert-base-parsbert-uncased. Creating a new one with mean pooling.

In [7]:
umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

In [8]:
cluster_model = HDBSCAN(
    min_cluster_size=20,
    metric="euclidean",
    prediction_data=True
)

In [25]:
persian_stopwords = list(
    stopwords.stopwords("fa")
)

persian_stopwords.extend([
    "ایسنا",
    "گزارش"
])

vectorizer_model = CountVectorizer(
    stop_words=persian_stopwords,
    ngram_range=(1, 2),
    min_df=5
)

In [26]:
topic_model = BERTopic(

    embedding_model=embedding_model,

    umap_model=umap_model,

    hdbscan_model=cluster_model,

    vectorizer_model=vectorizer_model,

    language=None,

    calculate_probabilities=True,

    verbose=True
)

In [27]:
output_dir = Path("outputs")
output_dir.mkdir(exist_ok=True)

print(output_dir)

outputs

In [28]:
start = time.time()

topics, probabilities = topic_model.fit_transform(
    documents
)

end = time.time()

print(f"Execution Time: {end - start:.2f} seconds")

2026-07-10 19:34:18,843 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 187/187 [02:39<00:00,  1.17it/s]
2026-07-10 19:36:59,168 - BERTopic - Embedding - Completed ✓
2026-07-10 19:36:59,169 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-07-10 19:37:29,355 - BERTopic - Dimensionality - Completed ✓
2026-07-10 19:37:29,356 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-07-10 19:37:32,582 - BERTopic - Cluster - Completed ✓
2026-07-10 19:37:32,598 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-07-10 19:37:44,083 - BERTopic - Representation - Completed ✓

Execution Time: 208.84 seconds

In [ ]:
topic_info = topic_model.get_topic_info()

document_info = topic_model.get_document_info(
    documents
)
topic_freq = topic_model.get_topic_freq()

In [ ]:
display(topic_info.head())

display(document_info.head())

display(topic_freq.head())

In [ ]:
topic_info.to_csv(
    "../results/tables/topic_info.csv",
    index=False,
    encoding="utf-8-sig"
)

document_info.to_csv(
    "../results/tables/document_info.csv",
    index=False,
    encoding="utf-8-sig"
)

topic_freq.to_csv(
    "../results/tables/topic_frequency.csv",
    index=False,
    encoding="utf-8-sig"
)

In [ ]:
print(topic_info.columns)

print(document_info.columns)

print(topic_freq.columns)

In [31]:
topic_info.head(10)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1537,-1_ایران_کشور_ملی_تیم,"[ایران, کشور, ملی, تیم, پیام, انتهای, انتهای پ...",[به گزارش ایسنا، حجت الاسلام موحدی آزاد دادستا...
1,0,1015,0_فیلم_کتاب_آثار_موسیقی,"[فیلم, کتاب, آثار, موسیقی, اثر, جشنواره, نمایش...",[به دلیل همزمانی با رحلت امام خمینی(ره)، نمایش...
2,1,467,1_نفت_شرکت_افزایش_دلار,"[نفت, شرکت, افزایش, دلار, هوش, مصنوعی, هوش مصن...",[به گزارش ایسنا، بهای معاملات وست تگزاس اینترم...
3,2,270,2_دولت_مجلس_کشور_شورای,"[دولت, مجلس, کشور, شورای, دارو, بودجه, اقتصادی...",[به گزارش ایسنا، مجتبی یوسفی در نشست خبری در ت...
4,3,252,3_قضایی_قوه_قضاییه_قوه قضاییه,"[قضایی, قوه, قضاییه, قوه قضاییه, رسیدگی, قانون...",[به گزارش ایسنا، حجت الاسلام و المسلمین خلیلی ...
5,4,187,4_اسلامی_انقلاب_ملت_ایران,"[اسلامی, انقلاب, ملت, ایران, حضرت, شهید, انقلا...",[به گزارش ایسنا، متن پیام ذبیحالله خدائیان، رئ...
6,5,180,5_برق_مصرف_آب_انرژی,"[برق, مصرف, آب, انرژی, تولید, کشور, صنعت, نیرو...",[به گزارش ایسنا، مصطفی رجبی مشهدی- معاون برق و...
7,6,145,6_بازی_تیم_بازیکنان_فوتبال,"[بازی, تیم, بازیکنان, فوتبال, استقلال, باشگاه,...",[به گزارش ایسنا و به نقل از رسانه رسمی باشگاه ...
8,7,124,7_آموزش_آموزشی_پرورش_آموزش پرورش,"[آموزش, آموزشی, پرورش, آموزش پرورش, مدارس, دان...",[به گزارش ایسنا، علیرضا کاظمی در برنامه گفتوگو...
9,8,114,8_سپاه_ارتش_عملیات_فروند,"[سپاه, ارتش, عملیات, فروند, سپاه پاسداران, آمر...",[به گزارش ایسنا، سرهنگ دوم پاسدار ابراهیم ذوال...

In [46]:
document_info.head()

,Document,Topic,Name,Representation,Representative_Docs,Top_n_words,Probability,Representative_document
0,به گزارش ایسنا، با اعلام فدراسیون فوتبال، تیم ...,-1,-1_ایران_کشور_ملی_تیم,"[ایران, کشور, ملی, تیم, پیام, انتهای, انتهای پ...",[به گزارش ایسنا، حجت الاسلام موحدی آزاد دادستا...,ایران - کشور - ملی - تیم - پیام - انتهای - انت...,0.422309,False
1,به گزارش ایسنا، اکبر کارگرجم بازیکن سابق استقل...,12,12_باشگاه_استقلال_پرسپولیس_ورزشگاه,"[باشگاه, استقلال, پرسپولیس, ورزشگاه, تیم, فوتب...",[به گزارش ایسنا، تیم فوتبال استقلال روز بیستوی...,باشگاه - استقلال - پرسپولیس - ورزشگاه - تیم - ...,0.385935,False
2,به گزارش ایسنا، هفته پنجم رقابتهای لیگ آزادگان...,-1,-1_ایران_کشور_ملی_تیم,"[ایران, کشور, ملی, تیم, پیام, انتهای, انتهای پ...",[به گزارش ایسنا، حجت الاسلام موحدی آزاد دادستا...,ایران - کشور - ملی - تیم - پیام - انتهای - انت...,0.852754,False
3,طبق اعلام نقی نصیری، مدیرعامل باشگاه مس سونگون...,12,12_باشگاه_استقلال_پرسپولیس_ورزشگاه,"[باشگاه, استقلال, پرسپولیس, ورزشگاه, تیم, فوتب...",[به گزارش ایسنا، تیم فوتبال استقلال روز بیستوی...,باشگاه - استقلال - پرسپولیس - ورزشگاه - تیم - ...,0.374967,False
4,این مسابقه از هفته پنجم لیگ برتر فوتبال کشور، ...,-1,-1_ایران_کشور_ملی_تیم,"[ایران, کشور, ملی, تیم, پیام, انتهای, انتهای پ...",[به گزارش ایسنا، حجت الاسلام موحدی آزاد دادستا...,ایران - کشور - ملی - تیم - پیام - انتهای - انت...,0.367262,False

In [33]:
topic_info[["Topic", "Count"]]

    Topic  Count
0      -1   1537
1       0   1015
2       1    467
3       2    270
4       3    252
5       4    187
6       5    180
7       6    145
8       7    124
9       8    114
10      9    102
11     10    101
12     11     99
13     12     84
14     13     84
15     14     79
16     15     79
17     16     62
18     17     60
19     18     58
20     19     58
21     20     54
22     21     48
23     22     47
24     23     41
25     24     41
26     25     41
27     26     40
28     27     40
29     28     36
30     29     34
31     30     32
32     31     32
33     32     32
34     33     29
35     34     29
36     35     29
37     36     29
38     37     29
39     38     28
40     39     28
41     40     25
42     41     23
43     42     23
44     43     22

In [39]:
n_docs = len(documents)
n_topics = len(topic_info) - 1
n_outliers = np.sum(np.array(topics) == -1)

print(f"Number of documents : {n_docs}")
print(f"Number of topics    : {n_topics}")
print(f"Outlier documents   : {n_outliers}")
print(f"Outlier percentage  : {100*n_outliers/n_docs:.2f}%")

Number of documents : 5969
Number of topics    : 44
Outlier documents   : 1537
Outlier percentage  : 25.75%

In [47]:
for topic in topic_info.Topic:

    if topic == -1:
        continue

    print("=" * 80)

    print(f"Topic {topic}")

    print(topic_model.get_topic(topic))

================================================================================
Topic 0
[('فیلم', 0.019580062171180284), ('کتاب', 0.01836706711512311), ('آثار', 0.014752007493731388), ('موسیقی', 0.013723242610700964), ('اثر', 0.013059025955017813), ('جشنواره', 0.013031008248922242), ('نمایش', 0.012866657914493715), ('میشود', 0.012297825582112978), ('تئاتر', 0.011402505608185195), ('هنر', 0.011020965379903443)]
================================================================================
Topic 1
[('نفت', 0.02807786498015879), ('شرکت', 0.0224958048447965), ('افزایش', 0.019444187523877575), ('دلار', 0.018535520329732123), ('هوش', 0.017388838902630564), ('مصنوعی', 0.017247305180603873), ('هوش مصنوعی', 0.017190181401879775), ('بشکه', 0.017013331857854374), ('آمریکا', 0.01683421966781469), ('کاهش', 0.015270530117700876)]
================================================================================
Topic 2
[('دولت', 0.019821041573463597), ('مجلس', 0.017156985871070826), ('کشور', 0.0145989747553339), ('شورای', 0.012191971043450107), ('دارو', 0.010683552471191203), ('بودجه', 0.010456176319961591), ('اقتصادی', 0.01038791931871779), ('ارز', 0.010061983592930835), ('افزایش', 0.009924040782363948), ('ادامه', 0.009799195031388977)]
================================================================================
Topic 3
[('قضایی', 0.029814525012291624), ('قوه', 0.026310159025046714), ('قضاییه', 0.023587709378622746), ('قوه قضاییه', 0.02356648780116649), ('رسیدگی', 0.017729304274908028), ('قانون', 0.015630158132834207), ('دادگستری', 0.01554810750475352), ('استان', 0.01490628484079708), ('پرونده', 0.014056855656134466), ('کشور', 0.013992000197843241)]
================================================================================
Topic 4
[('اسلامی', 0.039146972572165685), ('انقلاب', 0.02605302779801854), ('ملت', 0.025359175166306713), ('ایران', 0.02431502681619959), ('حضرت', 0.021858849618793055), ('شهید', 0.020996262180740684), ('انقلاب اسلامی', 0.020342136985210837), ('الله', 0.019807747597637024), ('شهادت', 0.019711067811713823), ('خامنهای', 0.016888619645310587)]
================================================================================
Topic 5
[('برق', 0.0668567556804975), ('مصرف', 0.04093978981510836), ('آب', 0.03354381664886302), ('انرژی', 0.02453430329436541), ('تولید', 0.019665236187538675), ('کشور', 0.019233832507666478), ('صنعت', 0.019199517262671637), ('نیرو', 0.01837881461281856), ('نیروگاه', 0.01764448733063128), ('مدیریت', 0.01729156381769279)]
================================================================================
Topic 6
[('بازی', 0.07050055963349681), ('تیم', 0.057089864457813354), ('بازیکنان', 0.047169384791396436), ('فوتبال', 0.044552033721726635), ('استقلال', 0.041097004220549994), ('باشگاه', 0.028398216165915455), ('خوبی', 0.0272905286564735), ('لیگ', 0.026162440811505774), ('بازیکن', 0.024521017683661543), ('خوزستان', 0.024141134420216346)]
================================================================================
Topic 7
[('آموزش', 0.04662928912422151), ('آموزشی', 0.03700697371828708), ('پرورش', 0.032864580090490245), ('آموزش پرورش', 0.03204193996130532), ('مدارس', 0.0304196484661922), ('دانشآموزان', 0.030387509093944342), ('مدرسه', 0.024207405921596127), ('تربیت', 0.015393330222549404), ('اشاره', 0.014674245714121466), ('آموزشوپرورش', 0.014437317583901628)]
================================================================================
Topic 8
[('سپاه', 0.04533400138707084), ('ارتش', 0.04508984953489989), ('عملیات', 0.03689518843111639), ('فروند', 0.029975199757046975), ('سپاه پاسداران', 0.02996852269003286), ('آمریکایی', 0.029183763392926856), ('پاسداران', 0.028818888009713717), ('اسلامی', 0.02867059059369997), ('دریایی', 0.02848671260913371), ('نیروی', 0.02764984073193187)]
================================================================================
Topic 9
[('وزن', 0.07521480548460638), ('مدال', 0.0703486663919579), ('جهان', 0.05789442043073924), ('کیلوگرم', 0.05602537882128604), ('دارنده', 0.05142745474791725), ('برنز', 0.043913777930598474), ('برتری', 0.04387194793307424), ('دارنده مدال', 0.04381388835444004), ('کشتی', 0.04011725000404543), ('نهایی', 0.038135613076521045)]
================================================================================
Topic 10
[('امام', 0.02636300480572004), ('شهید', 0.025835239891864255), ('انقلاب', 0.02322778899285202), ('اسلامی', 0.022282974391033796), ('ملت', 0.021859999134512788), ('جنگ', 0.01879844739099611), ('ایران', 0.018610667562862924), ('دشمن', 0.018297391895490383), ('ارتش', 0.01489590870572426), ('سپاه', 0.014602152681152685)]
================================================================================
Topic 11
[('ست', 0.07930443882315819), ('۲۵', 0.06513389202917384), ('ساعت', 0.05744708027116146), ('۳۰', 0.04524995094749202), ('شهریور', 0.038997665533336515), ('ایران', 0.038661404424225894), ('لهستان', 0.03750270310691766), ('تیم', 0.03710292841528634), ('والیبال', 0.0364488717307361), ('ایتالیا', 0.03621961876963589)]
================================================================================
Topic 12
[('باشگاه', 0.08571901378029968), ('استقلال', 0.08363292191071213), ('پرسپولیس', 0.07051939916439302), ('ورزشگاه', 0.0663351049463247), ('تیم', 0.047165387524724836), ('فوتبال', 0.046094879234387605), ('لیگ', 0.04084676107116402), ('خوزستان', 0.033407884150867886), ('انتهای پیام', 0.030198112469196747), ('انتهای', 0.030046855986367336)]
================================================================================
Topic 13
[('میتواند', 0.028074968142802047), ('مصرف', 0.023276579844438205), ('بدن', 0.022455114701191152), ('آب', 0.02227841539161739), ('توصیه', 0.02111051045615884), ('علائم', 0.0203359518221641), ('مواد', 0.01923568129919379), ('خواب', 0.01852520834274944), ('پزشک', 0.018246850859254628), ('افراد', 0.01805298408167296)]
================================================================================
Topic 14
[('تیم', 0.07658392032459241), ('بازی', 0.05366564502550253), ('تیم ملی', 0.05303096337076122), ('والیبال', 0.052300065907917116), ('ملی', 0.040621463652204724), ('بازیکنان', 0.034228680267405893), ('ملی والیبال', 0.028681889882543377), ('ایران', 0.027652080508557185), ('والیبال ایران', 0.025209370248977497), ('پیاتزا', 0.024429281677623777)]
================================================================================
Topic 15
[('کشتی', 0.06887456314676099), ('المپیک', 0.05257825369748431), ('مدال', 0.04645888961515479), ('مسابقات', 0.038247439296256514), ('قهرمانی', 0.03690641074287146), ('جهان', 0.03618915124877338), ('جهانی', 0.03504641842126141), ('وزن', 0.03395981700889888), ('کیلوگرم', 0.030473719992406993), ('کشتیگیر', 0.03010595372701731)]
================================================================================
Topic 16
[('ماده', 0.031712571569402), ('قانون', 0.031264495270915134), ('تسهیلات', 0.024964012919753847), ('تبصره', 0.02316358442705939), ('بند', 0.021971873234473194), ('مورخ', 0.020516107382133268), ('بانک', 0.016932118422157832), ('مذکور', 0.016562024513078297), ('ارزی', 0.015273729094926044), ('بیمه', 0.015019202835323394)]
================================================================================
Topic 17
[('تیم', 0.05061874198050685), ('تیم ملی', 0.048957025289777585), ('ایران', 0.03928544343332419), ('ملی', 0.0388380289593688), ('کوارتر', 0.03420299705253789), ('مسابقات', 0.033494820182650806), ('آسیا', 0.0301761262180911), ('۱۶', 0.029065259841345743), ('رقابتها', 0.02708477191185417), ('مرحله', 0.02617314702499938)]
================================================================================
Topic 18
[('قیمتی', 0.15110916126475002), ('تغییرات', 0.14040464629655203), ('درصد', 0.10328584863199948), ('دلار', 0.09059034074694808), ('درصد کاهش', 0.08990681337881817), ('۲۴ ساعت', 0.08773587979582814), ('قیمت', 0.08015670592423335), ('۲۴', 0.0790588249272606), ('کاهش', 0.06902499555342716), ('درصد افزایش', 0.06661342303928469)]
================================================================================
Topic 19
[('درصد', 0.06555066413295743), ('تورم', 0.05629018175722923), ('نرخ', 0.048477056545561024), ('ماه', 0.03862337549756833), ('نرخ تورم', 0.034558304056156196), ('شاخص', 0.034091155402300614), ('رشد', 0.03085697923419729), ('دلار', 0.028836072749902693), ('نفر', 0.028791972636485145), ('نسبت', 0.02725893641439673)]
================================================================================
Topic 20
[('آموزش', 0.06059569720337467), ('آموزش پرورش', 0.04684403717474495), ('پرورش', 0.045676558965596366), ('مدارس', 0.0369676386270653), ('دانش', 0.036738399694037006), ('آزمون', 0.036668177896305394), ('آموزان', 0.03649777081914207), ('دانش آموزان', 0.032716932781267596), ('مدرسه', 0.026951179943167865), ('وزارت آموزش', 0.025342929446644773)]
================================================================================
Topic 21
[('پزشکی', 0.04120223101715566), ('بهداشت', 0.034917012623992535), ('سلامت', 0.03239861137668167), ('درمان', 0.02683366689430507), ('واکسن', 0.024786462431510562), ('دارو', 0.02408342931399887), ('کرونا', 0.023193327474142243), ('وزارت بهداشت', 0.020633526950029894), ('جمعیت', 0.018185768752828253), ('کشور', 0.017790315607062502)]
================================================================================
Topic 22
[('کاربری شبکه', 0.08458381040440775), ('ایکس', 0.08280636125617716), ('حساب کاربری', 0.08280550768448204), ('شبکه اجتماعی', 0.08160241761413708), ('اجتماعی ایکس', 0.08115385585405745), ('نوشت', 0.08017674351809696), ('کاربری', 0.07545548559790109), ('ایکس نوشت', 0.06807226144495823), ('حساب', 0.06456523781279369), ('شبکه', 0.05759415464536474)]
================================================================================
Topic 23
[('خبرنگار', 0.8752378419169093), ('عماد', 0.5947420093029079), ('نعمتی', 0.5765113014392973), ('یزدان', 0.4459930027255417), ('قربانی', 0.3534426837487336), ('نگار', 0.20146794419695319), ('ندا', 0.19589219374903669), ('برزگر', 0.18986501349650278), ('حنانه', 0.18499430074645626), ('کرمانی', 0.16678221087170939)]
================================================================================
Topic 24
[('قهرمانی', 0.04550452381904978), ('کشتی', 0.04117768971541711), ('ایران', 0.03764450676647486), ('تبریک', 0.0365170023107112), ('ورزش', 0.03248980500286982), ('ملی کشتی', 0.031260691898130556), ('کشورمان', 0.02921360184856896), ('جوانان', 0.026775752866150488), ('پیام', 0.026275275845793863), ('فرنگی', 0.025974551120473876)]
================================================================================
Topic 25
[('ثبتنام', 0.05551255214920834), ('آزمون', 0.05519774013119415), ('تحصیلی', 0.055162695316060675), ('دانش', 0.05477663206850977), ('ثبت', 0.05210067559438978), ('دانش آموزان', 0.04818058926203948), ('آموزان', 0.0478311807201648), ('مدارس', 0.046129823583507375), ('پایه', 0.03289430602399387), ('سامانه', 0.030448997835384642)]
================================================================================
Topic 26
[('میناب', 0.05548588730037672), ('ایران', 0.04140348524600768), ('خون', 0.03828787057095748), ('نوشت', 0.0377170479683142), ('خاک', 0.03472045675503037), ('جان', 0.03228127492861358), ('داغ', 0.03224954964738864), ('سرزمین', 0.029010324889325145), ('دل', 0.025721470144831393), ('باد', 0.02570230308062531)]
================================================================================
Topic 27
[('نتیجه', 0.10443423212260537), ('وزن', 0.09383871207541242), ('دور', 0.08794070695216616), ('کیلوگرم', 0.08709288880574247), ('مغلوب', 0.08246063504201541), ('صفر', 0.08198242955676274), ('مرحله', 0.0738359941539899), ('دیدار', 0.06793196871946518), ('نهایی', 0.054334442086376854), ('شکست', 0.05194030937025056)]
================================================================================
Topic 28
[('شیوع', 0.03813123954345716), ('واکسن', 0.03771120071814279), ('جهانی بهداشت', 0.0368405622867255), ('بهداشت', 0.03539966990598294), ('سازمان جهانی', 0.03463518391745863), ('بیماری', 0.030131697793790897), ('نفر', 0.027177603393265543), ('ویروس', 0.026971236110242755), ('سازمان', 0.026028826619069034), ('جهانی', 0.024544333250971138)]
================================================================================
Topic 29
[('توسعه', 0.020098726520571625), ('پست', 0.019235007061205), ('کشور', 0.017389518699038608), ('شرکت ملی', 0.015743702343037735), ('اشاره', 0.015103328769848915), ('پستی', 0.015093332725551939), ('حوزه', 0.014268753403064268), ('پروژه', 0.013995220418786732), ('شرکت', 0.013605248399164414), ('دانشگاه', 0.01331259196900773)]
================================================================================
Topic 30
[('دانش آموز', 0.044052689828118004), ('آموز', 0.04346758269100073), ('حادثه', 0.041352117988964196), ('آتش', 0.03982623465757999), ('حمله', 0.038551471417038415), ('عملیات', 0.03779929736168081), ('شهید', 0.03548789087543279), ('مجروح', 0.03000641103592908), ('دانش', 0.02923077431189998), ('مدرسه', 0.0270654021963012)]
================================================================================
Topic 31
[('امتیاز', 0.07657931432207797), ('ایران', 0.06855702623081945), ('گل', 0.04667213643412495), ('کوارتر', 0.040917689118927555), ('ست', 0.038509085577744094), ('تیم', 0.037421706655819884), ('بازی', 0.03586766243608293), ('امتیازی', 0.02991685975607906), ('تیم ملی', 0.028387323003656498), ('اختلاف', 0.028263954303163513)]
================================================================================
Topic 32
[('تیم', 0.0671937116629497), ('بازی', 0.0547333379160238), ('قهرمانی', 0.048028354084799815), ('لیگ', 0.04762105662235235), ('فصل', 0.04172957862791501), ('تیم ملی', 0.036338651225634906), ('ملی', 0.031533249528881105), ('بازیکن', 0.030775398745366205), ('والیبال', 0.028266698403344215), ('مسابقات', 0.025006980232235645)]
================================================================================
Topic 33
[('ایران', 0.03265536389135886), ('آمریکا', 0.032552155463331865), ('جنگ', 0.027258151944044122), ('اسناد', 0.022583556583247906), ('نظامی', 0.01839849710412398), ('چین', 0.017259674893846708), ('سیاسی', 0.015912602408324154), ('عراق', 0.015424835899028174), ('رژیم', 0.014294558517553907), ('بینالمللی', 0.01411070720454046)]
================================================================================
Topic 34
[('اونس', 0.1198764056603229), ('طلا', 0.09195332081578342), ('دلار', 0.08846350744016365), ('سنت', 0.08842025255338994), ('درصد', 0.06927996703413768), ('افزایش', 0.06720922054183247), ('نرخ بهره', 0.06609982991273698), ('کاهش', 0.06542377454131967), ('قیمت', 0.06110180521999044), ('بهره', 0.0567881375522471)]
================================================================================
Topic 35
[('خبرنگار', 0.6260825438529717), ('ذوالفقاری', 0.5941415401712672), ('حنانه', 0.5293267583402252), ('مترجم', 0.5084331971571566), ('کرمانی', 0.477216253005183), ('شعبان', 0.3662715062898905), ('عسل', 0.3642691029883085), ('مریم', 0.3271687222730675), ('همتی', 0.22062512431054881), ('محمد', 0.18076070165824523)]
================================================================================
Topic 36
[('کیلوگرم', 0.14852664099451088), ('اوزان', 0.08287763622702543), ('وزن', 0.0731547003647283), ('مسابقات', 0.06022053837619757), ('کشتی', 0.058745660701180744), ('۳۰', 0.055968815631345745), ('دور', 0.04911956280846999), ('ساعت', 0.04193713189147285), ('کیلوگرم کشتی', 0.03883225376909217), ('کشتی آزاد', 0.03288397005139322)]
================================================================================
Topic 37
[('تیم', 0.04210988532347669), ('تیم ملی', 0.04062749202299364), ('فدراسیون', 0.03971153985445952), ('ملی', 0.03849009544607079), ('مسابقات', 0.03783704745854432), ('کشتی', 0.028158056788399426), ('قهرمانی', 0.0270818960660842), ('آسیایی', 0.024888900747047773), ('المپیک', 0.024181256279293645), ('کسب', 0.022534479919319148)]
================================================================================
Topic 38
[('حقوق', 0.08275091582468212), ('بشر', 0.052588040387508916), ('حقوق بشر', 0.05159289047615334), ('نقض', 0.04387482290123875), ('بینالمللی', 0.03973515337167619), ('بشردوستانه', 0.02792519138298221), ('حقوق بینالملل', 0.02758938013680698), ('ستاد حقوق', 0.026546674965777634), ('غیرنظامی', 0.026401935120242723), ('بینالملل', 0.025874466029245417)]
================================================================================
Topic 39
[('پخش', 0.08012472063741136), ('ساعت', 0.07883941203739527), ('ورزش', 0.06464769574838974), ('سیما', 0.06067049328605974), ('گزارشگری', 0.05858115630053197), ('شبکه', 0.05071661090383035), ('شهریور', 0.049659645372738974), ('زنده', 0.049069694228644115), ('والیبال', 0.04828802716592256), ('۳۰', 0.04767698591909829)]
================================================================================
Topic 40
[('ثبت', 0.09139859538579677), ('اسناد', 0.08466959075703988), ('سامانه', 0.06901025551606246), ('املاک', 0.06044958728385898), ('رسمی', 0.056292659282313376), ('سند', 0.053698038151998286), ('مالکیت', 0.04556825145970454), ('سازمان ثبت', 0.044463482121795246), ('ثبت اسناد', 0.042460531719700476), ('ادعا', 0.04098174615365389)]
================================================================================
Topic 41
[('جنابعالی', 0.07639386596147911), ('قوه', 0.04546959620008085), ('جناب', 0.04135833535502939), ('معظم', 0.03984747031691257), ('انتصاب', 0.03651145904636817), ('تبریک', 0.03263735935029857), ('اسلامی', 0.03167293315567041), ('مقام معظم', 0.02807066077000582), ('متن پیام', 0.027674040238085736), ('متن', 0.027460013525256947)]
================================================================================
Topic 42
[('سرطان', 0.05800964186093043), ('نتایج', 0.0382291828149544), ('خطر', 0.03635505119712939), ('تحقیق', 0.0357879609837352), ('میدهد', 0.026252337174249765), ('آلزایمر', 0.025400241050343338), ('آزمایش', 0.02539908204368676), ('بیماران', 0.02483482613305896), ('زوال', 0.024759571370233577), ('سلولهای', 0.024109343225209915)]
================================================================================
Topic 43
[('انتخابات', 0.08387751112470322), ('شوراهای', 0.04531144750470772), ('شوراها', 0.04088299326031393), ('شورای', 0.031630520900792755), ('روستا', 0.030588894118229487), ('شهر', 0.030210890676495836), ('شوراهای شهر', 0.026562460154091944), ('شهر روستا', 0.025855437592144592), ('ستاد انتخابات', 0.023585895342262166), ('وزارت کشور', 0.023283141242662817)]

In [48]:
fig = topic_model.visualize_topics()

fig.show()

In [49]:
fig.write_html(
    output_dir / "topic_map.html"
)

In [50]:
fig = topic_model.visualize_barchart(
    top_n_topics=20
)

fig.show()

In [51]:
fig.write_html(
    output_dir / "topic_barchart.html"
)

In [52]:
fig = topic_model.visualize_hierarchy()

fig.show()

In [53]:
fig.write_html(
    output_dir / "topic_hierarchy.html"
)

In [54]:
fig = topic_model.visualize_heatmap()

fig.show()

In [55]:
fig.write_html(
    output_dir / "topic_heatmap.html"
)

In [56]:
hierarchical_topics = topic_model.hierarchical_topics(
    documents
)

hierarchical_topics.head()

100%|██████████| 43/43 [00:00<00:00, 189.90it/s]

,Parent_ID,Parent_Name,Topics,Child_Left_ID,Child_Left_Name,Child_Right_ID,Child_Right_Name,Distance
42,86,ایران_سال_پیام_کشور_میشود,"[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,...",83,تیم_بازی_کیلوگرم_وزن_تیم ملی,85,سال_کشور_میشود_درصد_ایران,2.231506
41,85,سال_کشور_میشود_درصد_ایران,"[0, 1, 2, 3, 4, 5, 7, 8, 10, 13, 16, 18, 19, 2...",82,درصد_افزایش_کاهش_کشور_دلار,84,ایران_فیلم_کتاب_اسلامی_آثار,1.599454
40,84,ایران_فیلم_کتاب_اسلامی_آثار,"[0, 4, 8, 10, 22, 23, 24, 26, 30, 33, 35, 38, 41]",79,ایران_فیلم_کتاب_اسلامی_آثار,59,خبرنگار_عماد_نعمتی_حنانه_کرمانی,1.458414
39,83,تیم_بازی_کیلوگرم_وزن_تیم ملی,"[6, 9, 11, 12, 14, 15, 17, 27, 31, 32, 36, 37,...",78,تیم_بازی_تیم ملی_بازیکنان_ایران,60,کیلوگرم_وزن_مدال_کشتی_دور,1.432321
38,82,درصد_افزایش_کاهش_کشور_دلار,"[1, 2, 3, 5, 7, 13, 16, 18, 19, 20, 21, 25, 28...",66,درصد_دلار_افزایش_کاهش_قیمت,81,کشور_آموزش_سازمان_استان_اشاره,1.409833

In [57]:
hierarchical_topics.to_csv(
    output_dir / "hierarchical_topics.csv",
    index=False,
    encoding="utf-8-sig"
)

In [58]:
fig = topic_model.visualize_hierarchy(
    hierarchical_topics=hierarchical_topics
)

fig.show()

In [59]:
fig.write_html(
    output_dir / "topic_tree.html"
)

In [60]:
topic_labels = {}

for topic in topic_info.Topic:

    if topic == -1:
        continue

    words = topic_model.get_topic(topic)

    label = " | ".join(
        [word for word, _ in words[:3]]
    )

    topic_labels[topic] = label

In [61]:
topic_labels

{0: 'فیلم | کتاب | آثار',
 1: 'نفت | شرکت | افزایش',
 2: 'دولت | مجلس | کشور',
 3: 'قضایی | قوه | قضاییه',
 4: 'اسلامی | انقلاب | ملت',
 5: 'برق | مصرف | آب',
 6: 'بازی | تیم | بازیکنان',
 7: 'آموزش | آموزشی | پرورش',
 8: 'سپاه | ارتش | عملیات',
 9: 'وزن | مدال | جهان',
 10: 'امام | شهید | انقلاب',
 11: 'ست | ۲۵ | ساعت',
 12: 'باشگاه | استقلال | پرسپولیس',
 13: 'میتواند | مصرف | بدن',
 14: 'تیم | بازی | تیم ملی',
 15: 'کشتی | المپیک | مدال',
 16: 'ماده | قانون | تسهیلات',
 17: 'تیم | تیم ملی | ایران',
 18: 'قیمتی | تغییرات | درصد',
 19: 'درصد | تورم | نرخ',
 20: 'آموزش | آموزش پرورش | پرورش',
 21: 'پزشکی | بهداشت | سلامت',
 22: 'کاربری شبکه | ایکس | حساب کاربری',
 23: 'خبرنگار | عماد | نعمتی',
 24: 'قهرمانی | کشتی | ایران',
 25: 'ثبتنام | آزمون | تحصیلی',
 26: 'میناب | ایران | خون',
 27: 'نتیجه | وزن | دور',
 28: 'شیوع | واکسن | جهانی بهداشت',
 29: 'توسعه | پست | کشور',
 30: 'دانش آموز | آموز | حادثه',
 31: 'امتیاز | ایران | گل',
 32: 'تیم | بازی | قهرمانی',
 33: 'ایران | آمریکا | جنگ',
 34: 'اونس | طلا | دلار',
 35: 'خبرنگار | ذوالفقاری | حنانه',
 36: 'کیلوگرم | اوزان | وزن',
 37: 'تیم | تیم ملی | فدراسیون',
 38: 'حقوق | بشر | حقوق بشر',
 39: 'پخش | ساعت | ورزش',
 40: 'ثبت | اسناد | سامانه',
 41: 'جنابعالی | قوه | جناب',
 42: 'سرطان | نتایج | خطر',
 43: 'انتخابات | شوراهای | شوراها'}